spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagerapp
spring.datasource.username=postgres
spring.datasource.password=prj22327

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true